name: Terraform CI CD Pipeline for Deploying AWS ECS Resources

run-name: ${{github.actor}} has triggered the pipeline

on:
  push:
    branches:
      - "main"

env:
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./express-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/express-server-1:latest

  build-infra:
    name: aws-alb-ecs-terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        working-directory: ./AWS-ALB-ECS/
        run: terraform init

      - name: Terraform Validate
        id: validate
        working-directory: ./AWS-ALB-ECS/
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ./AWS-ALB-ECS/
        run: terraform plan

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        id: apply
        working-directory: ./AWS-ALB-ECS/
        run: terraform apply --auto-approve
